const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'playwright');
const assert = require('node:assert/strict');
const items = ['abcdefghijk', 'lmnopqrstuv', '123456789ab'].map((id, i) => ({ id, title: `Library ${i}`, channel: 'Fixture', channelId: 'UCabcdefghijklmnopqrstuv', duration: 40 }));
const sr = 24000, wav = Buffer.alloc(44 + sr * 40 * 2);
wav.write('RIFF'); wav.writeUInt32LE(wav.length - 8, 4); wav.write('WAVEfmt ', 8); wav.writeUInt32LE(16, 16);
wav.writeUInt16LE(1, 20); wav.writeUInt16LE(1, 22); wav.writeUInt32LE(sr, 24); wav.writeUInt32LE(sr * 2, 28);
wav.writeUInt16LE(2, 32); wav.writeUInt16LE(16, 34); wav.write('data', 36); wav.writeUInt32LE(wav.length - 44, 40);
(async () => {
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
    let subtitlesUnavailable = false;
    const errors = []; page.on('pageerror', e => errors.push(e.message)); page.on('dialog', d => d.accept());
    await page.addInitScript(() => { const Original = AudioContext; window.AudioContext = class extends Original { constructor(options) { super({ ...options, sinkId: { type: 'none' } }); } }; });
    await page.route('https://www.youtube-nocookie.com/**', route => route.fulfill({ contentType: 'text/html', body: '<html><body>Embedded player fixture</body></html>' }));
    await page.route('https://i.ytimg.com/**', route => route.fulfill({ contentType: 'image/svg+xml', body: '<svg xmlns="http://www.w3.org/2000/svg" width="320" height="180"/>' }));
    await page.route('**/api/**', async route => {
      const url = new URL(route.request().url()), path = url.pathname;
      if (path === '/api/modules') return route.fulfill({ json: { items: [] } });
      if (path.startsWith('/api/media/')) {
        const range = route.request().headers().range?.match(/bytes=(\d+)-(\d*)/), start = range ? Number(range[1]) : 0, end = range?.[2] ? Math.min(Number(range[2]), wav.length - 1) : wav.length - 1;
        return route.fulfill({ status: range ? 206 : 200, contentType: 'audio/wav', body: wav.subarray(start, end + 1), headers: { 'Accept-Ranges': 'bytes', ...(range ? { 'Content-Range': `bytes ${start}-${end}/${wav.length}` } : {}) } });
      }
      if (path === '/api/video/details') return route.fulfill({ json: { description: '公開概要 <script>not html</script>', chapters: [{ start: 10, title: '第二章' }] } });
      if (path === '/api/dubbing/subtitles') return route.fulfill(subtitlesUnavailable
        ? { status: 503, json: { error: { message: 'この動画の字幕を取得できませんでした。' } } }
        : { json: { cues: [{ start: 0, end: 30, text: 'テスト字幕' }] } });
      if (path === '/api/next') return route.fulfill({ json: { items: [items[1]] } });
      return route.fulfill({ json: { items, channelId: items[0].channelId, channel: 'Fixture', nextOffset: 24, hasMore: false } });
    });
    await page.goto(process.env.CLIPNEST_URL || 'http://127.0.0.1:8000');
    const menu = page.locator('.card-menu').first(); await menu.locator('summary').click(); await menu.getByRole('button', { name: '後で見る', exact: true }).click();
    await page.locator('#libraryButton').click();
    let library = page.getByRole('dialog', { name: 'マイライブラリ', exact: true });
    assert.equal(await library.locator('.library-row').count(), 1);
    await library.getByRole('textbox', { name: 'プレイリスト名', exact: true }).fill('My Playlist'); await library.getByRole('button', { name: '作成', exact: true }).click();
    assert.equal(await library.locator('.library-row').count(), 0);
    await library.getByRole('button', { name: '閉じる', exact: true }).click();
    await page.locator('.card-media').first().click();
    await page.waitForFunction(() => document.querySelector('audio').currentTime > 0.1);
    await page.locator('audio').evaluate(a => { a.currentTime = 12; });
    await page.waitForFunction(() => !document.querySelector('audio').seeking && document.querySelector('audio').currentTime >= 12);
    await page.locator('audio').evaluate(a => a.pause());
    await page.reload(); await page.locator('.card-media').first().click();
    await page.waitForFunction(() => document.querySelector('audio').currentTime >= 12);
    assert.equal(await page.locator('.watched-progress').count(), 1);
    await page.locator('#watchButton').click();
    let watch = page.getByRole('dialog', { name: '再生画面', exact: true });
    assert.equal(await watch.locator('#seek').count(), 1);
    assert.equal(await page.locator('#seek').count(), 1);
    assert.equal(await page.locator('#playerShell #audio').count(), 1);
    await watch.getByText('音声設定', { exact: true }).click();
    assert.equal(await page.locator('#volume').count(), 1);
    await watch.locator('#volume').fill('1.5');
    assert.equal(await watch.locator('#volumeValue').textContent(), '150%（ブースト）');
    await watch.locator('#forward5').click();
    await page.waitForFunction(() => { const a = document.querySelector('audio'); return !a.muted && !a.seeking && a.currentTime >= 17; });
    await watch.getByText('音声設定', { exact: true }).click();
    await watch.evaluate(d => { d.scrollTop = 0; });
    await page.screenshot({ path: '/tmp/clipnest-watch-open-desktop.png' });
    await page.setViewportSize({ width: 390, height: 844 });
    await watch.evaluate(d => { d.scrollTop = 0; });
    await page.screenshot({ path: '/tmp/clipnest-watch-open-mobile.png' });
    assert.ok(await watch.evaluate(d => d.scrollWidth <= d.clientWidth));
    await page.setViewportSize({ width: 1280, height: 900 });
    await watch.getByText('概要・チャプター', { exact: true }).click(); await watch.getByRole('button', { name: '概要を取得', exact: true }).click();
    await watch.getByRole('button', { name: '0:10 第二章' }).waitFor();
    assert.ok((await watch.locator('.video-description').textContent()).includes('<script>not html</script>'));
    await watch.getByText('字幕・文字起こし表示', { exact: true }).click(); await watch.getByRole('button', { name: '字幕を取得', exact: true }).click();
    await watch.locator('.transcript button').waitFor();
    await page.screenshot({ path: '/tmp/clipnest-watch-desktop.png' });
    subtitlesUnavailable = true;
    await watch.getByRole('button', { name: '字幕を取得', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('.transcript').textContent === 'この動画の字幕を取得できませんでした。');
    await watch.getByRole('button', { name: '映像を開く', exact: true }).click();
    assert.equal(await page.locator('audio').evaluate(a => a.paused), true);
    assert.ok((await watch.locator('iframe').getAttribute('src')).startsWith('https://www.youtube-nocookie.com/embed/abcdefghijk'));
    await watch.getByRole('button', { name: 'ミニ表示', exact: true }).click();
    await page.waitForTimeout(150);
    assert.equal(await page.locator('.watch-mini iframe').count(), 1);
    assert.equal(await page.locator('#playerShell #seek').count(), 1);
    assert.equal(await page.locator('#playerShell #volume').count(), 1);
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: '/tmp/clipnest-watch-mobile.png' });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.setViewportSize({ width: 1280, height: 900 });
    await watch.getByRole('button', { name: '音声モードへ戻る', exact: true }).click();
    assert.equal(await watch.locator('iframe').count(), 0);
    await watch.getByRole('button', { name: '通常表示', exact: true }).click();
    assert.equal(await watch.locator('#seek').count(), 1);
    await watch.getByRole('button', { name: 'Library 1を再生', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('.watch-dialog .watch-title')?.textContent === 'Library 1');
    assert.equal(await page.locator('.watch-dialog[open]').count(), 1);
    assert.equal(await watch.locator('#seek').count(), 1);
    assert.equal(await watch.locator('#volume').inputValue(), '1.5');
    await watch.getByRole('button', { name: '閉じる', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('#playerShell #seek') && document.querySelector('#playerShell #volume'));
    assert.equal(await page.locator('#volume').count(), 1);
    await menu.locator('summary').click(); await menu.getByRole('button', { name: '興味なし', exact: true }).click();
    assert.equal(await page.locator('.card-media').count(), 2);
    await page.reload(); await page.waitForFunction(() => document.querySelectorAll('.card-media').length === 2);
    await page.locator('.channel-avatar-button').first().click();
    await page.getByRole('searchbox', { name: 'チャンネル内検索' }).fill('Library 1');
    assert.equal(await page.locator('.card-media').count(), 1);
    await page.getByRole('button', { name: 'チャンネル動画を追加', exact: true }).click();
    await page.waitForFunction(() => ![...document.querySelectorAll('#sectionActions button')].some(b => b.textContent === 'チャンネル動画を追加' && !b.hidden));
    assert.deepEqual(errors, []);
    await page.setViewportSize({ width: 390, height: 844 }); await page.locator('#libraryButton').click();
    await page.screenshot({ path: '/tmp/clipnest-library-mobile.png' });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.getByRole('dialog', { name: 'マイライブラリ', exact: true }).getByRole('button', { name: '連続再生（キュー置換）', exact: true }).click();
    await page.waitForFunction(() => { const a = document.querySelector('audio'); return a.currentSrc.includes('abcdefghijk') && !a.paused; });
    assert.equal(await page.locator('#autoplayButton').getAttribute('aria-pressed'), 'true');
    assert.deepEqual(errors, []);
    console.log('PASS: watch later, playlist create, resume/progress, escaped description, captions, embed isolation, mini mode, exclusion, channel filter/paging, mobile');
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exitCode = 1; });
