import assert from 'node:assert/strict';
import { LocalLibrary } from '../static/core/local_library.js';
const map = new Map(), storage = { getItem: key => map.get(key) ?? null, setItem: (key, value) => map.set(key, value) };
const item = { id: 'abcdefghijk', title: '<script>safe</script>', duration: 120, channelId: 'UCabcdefghijklmnopqrstuv' };
const other = { ...item, id: 'lmnopqrstuv' };
const library = new LocalLibrary(storage);
library.add('later', item); library.add('later', item);
assert.equal(library.list('later').items.length, 1);
const list = library.create('Test'); library.add(list.id, item); library.add(list.id, other);
library.move(list.id, 1, -1); assert.equal(library.list(list.id).items[0].id, other.id);
library.rename(list.id, 'New'); assert.equal(library.list(list.id).name, 'New');
library.remember(item, 42, 120); assert.equal(library.resume(item), 42);
library.remember(item, 118, 120); assert.equal(library.resume(item), 0);
library.hide(item); assert.equal(library.visible(item), false); assert.equal(library.visible(other), true);
library.hide(item, true); assert.equal(library.visible(other), false);
const reopened = new LocalLibrary(storage); assert.equal(reopened.visible(other), false);
reopened.restoreHidden(); assert.equal(reopened.visible(item), true);
reopened.delete(list.id); assert.throws(() => reopened.list(list.id)); assert.throws(() => reopened.delete('later'));
assert.throws(() => library.add('later', { id: '../unsafe' }));
storage.setItem(library.key, '{invalid'); assert.equal(new LocalLibrary(storage).list('later').items.length, 0);
console.log('PASS: local playlists, deduplication, ordering, persistence, resume completion, exclusions, validation');
